<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskManager.DAL\TaskManager.DAL.csproj" />
    <ProjectReference Include="..\TaskManager.DTO\TaskManager.DTO.csproj" />
    <ProjectReference Include="..\TaskManager.HELPERS\TaskManager.HELPERS.csproj" />
  </ItemGroup>

</Project>
