<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="ControllerResponse\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskManager.DAL\TaskManager.DAL.csproj" />
  </ItemGroup>

</Project>
